// Tarea 2A.3 — las doce clases del SRD 5.1, su progresión y su única subclase.
//
// **Atribución:** material del System Reference Document 5.1, © Wizards of the Coast LLC,
// CC BY 4.0. Nombres traducidos al español y reorganizados como datos estructurados — una
// modificación, declarada en `NOTICE.md` de la raíz.
//
// **Alcance declarado: se transcribe el NOMBRE de cada aptitud y el nivel al que llega, no su
// texto de reglas.** El plan pedía «aptitudes por nivel como texto» (§4.3); se entrega el
// nombre porque es lo que la hoja necesita enseñar («al nivel 5 ganas Ataque adicional») y
// porque traducir a mano el texto completo de doscientas aptitudes es exactamente donde una
// transcripción se llena de errores que ningún invariante puede cazar. Queda anotado como
// deuda en `docs/06-pendientes.md`.
//
// **Los niveles de mejora de característica NO están en `features`**: viven en `asiLevels`, y
// hay un invariante que comprueba que no se dupliquen. Repetir un dato es cómo empiezan a
// discrepar.

import { SKILLS, type SkillKey } from "@dnd/shared";
import type { ClassFeature, SrdClass } from "./types";

/** El bardo elige entre **todas**. Se escribe la lista entera y no `[]` con una nota: una lista
 * vacía con un comentario que dice «en realidad son todas» es exactamente la clase de dato que
 * un invariante no puede comprobar y una pantalla acaba pintando como «elige 3 de 0». */
const TODAS_LAS_HABILIDADES = Object.keys(SKILLS) as SkillKey[];

/** Atajo para que la tabla de progresión se lea como una tabla y no como un formulario. */
function f(level: number, key: string, name: string): ClassFeature {
  return { level, key, name };
}

const ASI_ESTANDAR = [4, 8, 12, 16, 19];

const HABILIDADES_BARBARO: SkillKey[] = [
  "animal-handling",
  "athletics",
  "intimidation",
  "nature",
  "perception",
  "survival",
];

export const SRD_CLASSES: SrdClass[] = [
  {
    key: "barbarian",
    name: "Bárbaro",
    hitDie: 12,
    saveProficiencies: ["str", "con"],
    armorProficiencies: ["Armadura ligera", "Armadura media", "Escudos"],
    weaponProficiencies: ["Armas sencillas", "Armas marciales"],
    skillChoice: { choose: 2, from: HABILIDADES_BARBARO },
    attacksPerAction: [{ fromLevel: 5, attacks: 2 }],
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "rage", "Furia"),
      f(1, "unarmored-defense", "Defensa sin armadura"),
      f(2, "reckless-attack", "Ataque temerario"),
      f(2, "danger-sense", "Sentido del peligro"),
      f(3, "primal-path", "Senda primaria"),
      f(5, "extra-attack", "Ataque adicional"),
      f(5, "fast-movement", "Movimiento rápido"),
      f(7, "feral-instinct", "Instinto salvaje"),
      f(9, "brutal-critical-1", "Crítico brutal (1 dado)"),
      f(11, "relentless-rage", "Furia implacable"),
      f(13, "brutal-critical-2", "Crítico brutal (2 dados)"),
      f(15, "persistent-rage", "Furia persistente"),
      f(17, "brutal-critical-3", "Crítico brutal (3 dados)"),
      f(18, "indomitable-might", "Poderío indomable"),
      f(20, "primal-champion", "Campeón primario"),
    ],
    subclasses: [
      {
        key: "berserker",
        name: "Senda del berserker",
        chosenAtLevel: 3,
        features: [
          f(3, "frenzy", "Frenesí"),
          f(6, "mindless-rage", "Furia irracional"),
          f(10, "intimidating-presence", "Presencia intimidante"),
          f(14, "retaliation", "Represalia"),
        ],
      },
    ],
  },
  {
    key: "bard",
    name: "Bardo",
    hitDie: 8,
    saveProficiencies: ["dex", "cha"],
    armorProficiencies: ["Armadura ligera"],
    weaponProficiencies: [
      "Armas sencillas",
      "Ballestas de mano",
      "Espadas largas",
      "Estoques",
      "Espadas cortas",
    ],
    skillChoice: { choose: 3, from: TODAS_LAS_HABILIDADES },
    spellcastingAbility: "cha",
    spellProgression: "FULL",
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "spellcasting", "Lanzamiento de conjuros"),
      f(1, "bardic-inspiration-d6", "Inspiración de bardo (d6)"),
      f(2, "jack-of-all-trades", "Aprendiz de todo"),
      f(2, "song-of-rest-d6", "Canción de descanso (d6)"),
      f(3, "bard-college", "Colegio de bardos"),
      f(3, "expertise-1", "Pericia"),
      f(5, "bardic-inspiration-d8", "Inspiración de bardo (d8)"),
      f(5, "font-of-inspiration", "Fuente de inspiración"),
      f(6, "countercharm", "Contraencanto"),
      f(9, "song-of-rest-d8", "Canción de descanso (d8)"),
      f(10, "bardic-inspiration-d10", "Inspiración de bardo (d10)"),
      f(10, "expertise-2", "Pericia"),
      f(10, "magical-secrets-1", "Secretos mágicos"),
      f(13, "song-of-rest-d10", "Canción de descanso (d10)"),
      f(14, "magical-secrets-2", "Secretos mágicos"),
      f(15, "bardic-inspiration-d12", "Inspiración de bardo (d12)"),
      f(17, "song-of-rest-d12", "Canción de descanso (d12)"),
      f(18, "magical-secrets-3", "Secretos mágicos"),
      f(20, "superior-inspiration", "Inspiración superior"),
    ],
    subclasses: [
      {
        key: "lore",
        name: "Colegio del conocimiento",
        chosenAtLevel: 3,
        features: [
          f(3, "bonus-proficiencies", "Competencias adicionales"),
          f(3, "cutting-words", "Palabras hirientes"),
          f(6, "additional-magical-secrets", "Secretos mágicos adicionales"),
          f(14, "peerless-skill", "Habilidad sin par"),
        ],
      },
    ],
  },
  {
    key: "cleric",
    name: "Clérigo",
    hitDie: 8,
    saveProficiencies: ["wis", "cha"],
    armorProficiencies: ["Armadura ligera", "Armadura media", "Escudos"],
    weaponProficiencies: ["Armas sencillas"],
    skillChoice: {
      choose: 2,
      from: ["history", "insight", "medicine", "persuasion", "religion"],
    },
    spellcastingAbility: "wis",
    spellProgression: "FULL",
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "spellcasting", "Lanzamiento de conjuros"),
      f(1, "divine-domain", "Dominio divino"),
      f(2, "channel-divinity-1", "Canalizar divinidad (1/descanso)"),
      f(5, "destroy-undead-cr-half", "Destruir muertos vivientes (VD 1/2)"),
      f(6, "channel-divinity-2", "Canalizar divinidad (2/descanso)"),
      f(8, "destroy-undead-cr-1", "Destruir muertos vivientes (VD 1)"),
      f(10, "divine-intervention", "Intervención divina"),
      f(11, "destroy-undead-cr-2", "Destruir muertos vivientes (VD 2)"),
      f(14, "destroy-undead-cr-3", "Destruir muertos vivientes (VD 3)"),
      f(17, "destroy-undead-cr-4", "Destruir muertos vivientes (VD 4)"),
      f(18, "channel-divinity-3", "Canalizar divinidad (3/descanso)"),
      f(20, "divine-intervention-improvement", "Intervención divina mejorada"),
    ],
    subclasses: [
      {
        key: "life-domain",
        name: "Dominio de la vida",
        chosenAtLevel: 1,
        features: [
          f(1, "bonus-proficiency", "Competencia adicional"),
          f(1, "disciple-of-life", "Discípulo de la vida"),
          f(2, "preserve-life", "Preservar la vida"),
          f(6, "blessed-healer", "Sanador bendito"),
          f(8, "divine-strike", "Golpe divino"),
          f(17, "supreme-healing", "Sanación suprema"),
        ],
      },
    ],
  },
  {
    key: "druid",
    name: "Druida",
    hitDie: 8,
    saveProficiencies: ["int", "wis"],
    armorProficiencies: [
      "Armadura ligera (no metálica)",
      "Armadura media (no metálica)",
      "Escudos (no metálicos)",
    ],
    weaponProficiencies: [
      "Clavas",
      "Dagas",
      "Dardos",
      "Jabalinas",
      "Mazas",
      "Bastones",
      "Cimitarras",
      "Hoces",
      "Hondas",
      "Lanzas",
    ],
    skillChoice: {
      choose: 2,
      from: [
        "arcana",
        "animal-handling",
        "insight",
        "medicine",
        "nature",
        "perception",
        "religion",
        "survival",
      ],
    },
    spellcastingAbility: "wis",
    spellProgression: "FULL",
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "druidic", "Drúidico"),
      f(1, "spellcasting", "Lanzamiento de conjuros"),
      f(2, "wild-shape", "Forma salvaje"),
      f(2, "druid-circle", "Círculo druídico"),
      f(4, "wild-shape-improvement-1", "Forma salvaje mejorada"),
      f(8, "wild-shape-improvement-2", "Forma salvaje mejorada"),
      f(18, "timeless-body", "Cuerpo eterno"),
      f(18, "beast-spells", "Conjuros bestiales"),
      f(20, "archdruid", "Archidruida"),
    ],
    subclasses: [
      {
        key: "circle-of-the-land",
        name: "Círculo de la tierra",
        chosenAtLevel: 2,
        features: [
          f(2, "bonus-cantrip", "Truco adicional"),
          f(2, "natural-recovery", "Recuperación natural"),
          f(3, "circle-spells", "Conjuros del círculo"),
          f(6, "lands-stride", "Zancada de la tierra"),
          f(10, "natures-ward", "Protección de la naturaleza"),
          f(14, "natures-sanctuary", "Santuario de la naturaleza"),
        ],
      },
    ],
  },
  {
    key: "fighter",
    name: "Guerrero",
    hitDie: 10,
    saveProficiencies: ["str", "con"],
    armorProficiencies: ["Toda armadura", "Escudos"],
    weaponProficiencies: ["Armas sencillas", "Armas marciales"],
    skillChoice: {
      choose: 2,
      from: [
        "acrobatics",
        "animal-handling",
        "athletics",
        "history",
        "insight",
        "intimidation",
        "perception",
        "survival",
      ],
    },
    // El guerrero es la única clase con **siete** mejoras de característica.
    attacksPerAction: [
      { fromLevel: 5, attacks: 2 },
      { fromLevel: 11, attacks: 3 },
      { fromLevel: 20, attacks: 4 },
    ],
    asiLevels: [4, 6, 8, 12, 14, 16, 19],
    features: [
      f(1, "fighting-style", "Estilo de combate"),
      f(1, "second-wind", "Nuevo aliento"),
      f(2, "action-surge-1", "Oleada de acción (un uso)"),
      f(3, "martial-archetype", "Arquetipo marcial"),
      f(5, "extra-attack-1", "Ataque adicional"),
      f(9, "indomitable-1", "Indomable (un uso)"),
      f(11, "extra-attack-2", "Ataque adicional (2)"),
      f(13, "indomitable-2", "Indomable (dos usos)"),
      f(17, "action-surge-2", "Oleada de acción (dos usos)"),
      f(17, "indomitable-3", "Indomable (tres usos)"),
      f(20, "extra-attack-3", "Ataque adicional (3)"),
    ],
    subclasses: [
      {
        key: "champion",
        name: "Campeón",
        chosenAtLevel: 3,
        features: [
          f(3, "improved-critical", "Crítico mejorado"),
          f(7, "remarkable-athlete", "Atleta excepcional"),
          f(10, "additional-fighting-style", "Estilo de combate adicional"),
          f(15, "superior-critical", "Crítico superior"),
          f(18, "survivor", "Superviviente"),
        ],
      },
    ],
  },
  {
    key: "monk",
    name: "Monje",
    hitDie: 8,
    saveProficiencies: ["str", "dex"],
    armorProficiencies: [],
    weaponProficiencies: ["Armas sencillas", "Espadas cortas"],
    skillChoice: {
      choose: 2,
      from: ["acrobatics", "athletics", "history", "insight", "religion", "stealth"],
    },
    attacksPerAction: [{ fromLevel: 5, attacks: 2 }],
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "unarmored-defense", "Defensa sin armadura"),
      f(1, "martial-arts", "Artes marciales"),
      f(2, "ki", "Ki"),
      f(2, "unarmored-movement", "Movimiento sin armadura"),
      f(3, "monastic-tradition", "Tradición monástica"),
      f(3, "deflect-missiles", "Desviar proyectiles"),
      f(4, "slow-fall", "Caída lenta"),
      f(5, "extra-attack", "Ataque adicional"),
      f(5, "stunning-strike", "Golpe aturdidor"),
      f(6, "ki-empowered-strikes", "Golpes potenciados por el ki"),
      f(7, "evasion", "Evasión"),
      f(7, "stillness-of-mind", "Quietud mental"),
      f(9, "unarmored-movement-improvement", "Movimiento sin armadura mejorado"),
      f(10, "purity-of-body", "Pureza corporal"),
      f(13, "tongue-of-the-sun-and-moon", "Lengua del sol y la luna"),
      f(14, "diamond-soul", "Alma de diamante"),
      f(15, "timeless-body", "Cuerpo eterno"),
      f(18, "empty-body", "Cuerpo vacío"),
      f(20, "perfect-self", "Ser perfecto"),
    ],
    subclasses: [
      {
        key: "open-hand",
        name: "Camino de la mano abierta",
        chosenAtLevel: 3,
        features: [
          f(3, "open-hand-technique", "Técnica de la mano abierta"),
          f(6, "wholeness-of-body", "Plenitud corporal"),
          f(11, "tranquility", "Tranquilidad"),
          f(17, "quivering-palm", "Palma trémula"),
        ],
      },
    ],
  },
  {
    key: "paladin",
    name: "Paladín",
    hitDie: 10,
    saveProficiencies: ["wis", "cha"],
    armorProficiencies: ["Toda armadura", "Escudos"],
    weaponProficiencies: ["Armas sencillas", "Armas marciales"],
    skillChoice: {
      choose: 2,
      from: ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"],
    },
    spellcastingAbility: "cha",
    // Desde el 2, no desde el 1. Antes esto era un comentario que el código no aplicaba.
    spellcastingFromLevel: 2,
    spellProgression: "HALF",
    attacksPerAction: [{ fromLevel: 5, attacks: 2 }],
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "divine-sense", "Sentido divino"),
      f(1, "lay-on-hands", "Imposición de manos"),
      f(2, "fighting-style", "Estilo de combate"),
      f(2, "spellcasting", "Lanzamiento de conjuros"),
      f(2, "divine-smite", "Castigo divino"),
      f(3, "divine-health", "Salud divina"),
      f(3, "sacred-oath", "Juramento sagrado"),
      f(5, "extra-attack", "Ataque adicional"),
      f(6, "aura-of-protection", "Aura de protección"),
      f(10, "aura-of-courage", "Aura de coraje"),
      f(11, "improved-divine-smite", "Castigo divino mejorado"),
      f(14, "cleansing-touch", "Toque purificador"),
      f(18, "aura-improvements", "Auras mejoradas"),
    ],
    subclasses: [
      {
        key: "oath-of-devotion",
        name: "Juramento de devoción",
        chosenAtLevel: 3,
        features: [
          f(3, "oath-spells", "Conjuros del juramento"),
          f(3, "channel-divinity", "Canalizar divinidad"),
          f(7, "aura-of-devotion", "Aura de devoción"),
          f(15, "purity-of-spirit", "Pureza de espíritu"),
          f(20, "holy-nimbus", "Nimbo sagrado"),
        ],
      },
    ],
  },
  {
    key: "ranger",
    name: "Explorador",
    hitDie: 10,
    saveProficiencies: ["str", "dex"],
    armorProficiencies: ["Armadura ligera", "Armadura media", "Escudos"],
    weaponProficiencies: ["Armas sencillas", "Armas marciales"],
    skillChoice: {
      choose: 3,
      from: [
        "animal-handling",
        "athletics",
        "insight",
        "investigation",
        "nature",
        "perception",
        "stealth",
        "survival",
      ],
    },
    spellcastingAbility: "wis",
    spellcastingFromLevel: 2,
    spellProgression: "HALF",
    attacksPerAction: [{ fromLevel: 5, attacks: 2 }],
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "favored-enemy", "Enemigo predilecto"),
      f(1, "natural-explorer", "Explorador natural"),
      f(2, "fighting-style", "Estilo de combate"),
      f(2, "spellcasting", "Lanzamiento de conjuros"),
      f(3, "ranger-archetype", "Arquetipo de explorador"),
      f(3, "primeval-awareness", "Percepción primigenia"),
      f(5, "extra-attack", "Ataque adicional"),
      f(6, "favored-enemy-improvement", "Enemigo predilecto y explorador natural mejorados"),
      f(8, "lands-stride", "Zancada de la tierra"),
      f(10, "natural-explorer-improvement", "Explorador natural mejorado"),
      f(10, "hide-in-plain-sight", "Ocultarse a plena vista"),
      f(14, "favored-enemy-improvement-2", "Enemigo predilecto mejorado"),
      f(14, "vanish", "Desvanecerse"),
      f(18, "feral-senses", "Sentidos salvajes"),
      f(20, "foe-slayer", "Matador de enemigos"),
    ],
    subclasses: [
      {
        key: "hunter",
        name: "Cazador",
        chosenAtLevel: 3,
        features: [
          f(3, "hunters-prey", "Presa del cazador"),
          f(7, "defensive-tactics", "Tácticas defensivas"),
          f(11, "multiattack", "Ataque múltiple"),
          f(15, "superior-hunters-defense", "Defensa superior del cazador"),
        ],
      },
    ],
  },
  {
    key: "rogue",
    name: "Pícaro",
    hitDie: 8,
    saveProficiencies: ["dex", "int"],
    armorProficiencies: ["Armadura ligera"],
    weaponProficiencies: [
      "Armas sencillas",
      "Ballestas de mano",
      "Espadas largas",
      "Estoques",
      "Espadas cortas",
    ],
    skillChoice: {
      choose: 4,
      from: [
        "acrobatics",
        "athletics",
        "deception",
        "insight",
        "intimidation",
        "investigation",
        "perception",
        "performance",
        "persuasion",
        "sleight-of-hand",
        "stealth",
      ],
    },
    // El pícaro tiene una mejora extra al nivel 10.
    asiLevels: [4, 8, 10, 12, 16, 19],
    features: [
      f(1, "expertise-1", "Pericia"),
      f(1, "sneak-attack", "Ataque furtivo"),
      f(1, "thieves-cant", "Jerga de ladrones"),
      f(2, "cunning-action", "Acción astuta"),
      f(3, "roguish-archetype", "Arquetipo de pícaro"),
      f(5, "uncanny-dodge", "Esquiva asombrosa"),
      f(6, "expertise-2", "Pericia"),
      f(7, "evasion", "Evasión"),
      f(11, "reliable-talent", "Talento fiable"),
      f(14, "blindsense", "Sentido ciego"),
      f(15, "slippery-mind", "Mente escurridiza"),
      f(18, "elusive", "Elusivo"),
      f(20, "stroke-of-luck", "Golpe de suerte"),
    ],
    subclasses: [
      {
        key: "thief",
        name: "Ladrón",
        chosenAtLevel: 3,
        features: [
          f(3, "fast-hands", "Manos rápidas"),
          f(3, "second-story-work", "Trabajo de altura"),
          f(9, "supreme-sneak", "Sigilo supremo"),
          f(13, "use-magic-device", "Usar objeto mágico"),
          f(17, "thiefs-reflexes", "Reflejos de ladrón"),
        ],
      },
    ],
  },
  {
    key: "sorcerer",
    name: "Hechicero",
    hitDie: 6,
    saveProficiencies: ["con", "cha"],
    armorProficiencies: [],
    weaponProficiencies: ["Dagas", "Dardos", "Hondas", "Bastones", "Ballestas ligeras"],
    skillChoice: {
      choose: 2,
      from: ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"],
    },
    spellcastingAbility: "cha",
    spellProgression: "FULL",
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "spellcasting", "Lanzamiento de conjuros"),
      f(1, "sorcerous-origin", "Origen hechicero"),
      f(2, "font-of-magic", "Fuente de magia"),
      f(3, "metamagic-1", "Metamagia"),
      f(10, "metamagic-2", "Metamagia"),
      f(17, "metamagic-3", "Metamagia"),
      f(20, "sorcerous-restoration", "Restauración hechicera"),
    ],
    subclasses: [
      {
        key: "draconic-bloodline",
        name: "Linaje dracónico",
        chosenAtLevel: 1,
        features: [
          f(1, "dragon-ancestor", "Ancestro dragón"),
          f(1, "draconic-resilience", "Resistencia dracónica"),
          f(6, "elemental-affinity", "Afinidad elemental"),
          f(14, "dragon-wings", "Alas de dragón"),
          f(18, "draconic-presence", "Presencia dracónica"),
        ],
      },
    ],
  },
  {
    key: "warlock",
    name: "Brujo",
    hitDie: 8,
    saveProficiencies: ["wis", "cha"],
    armorProficiencies: ["Armadura ligera"],
    weaponProficiencies: ["Armas sencillas"],
    skillChoice: {
      choose: 2,
      from: [
        "arcana",
        "deception",
        "history",
        "intimidation",
        "investigation",
        "nature",
        "religion",
      ],
    },
    spellcastingAbility: "cha",
    spellProgression: "PACT",
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "otherworldly-patron", "Patrón de otro mundo"),
      f(1, "pact-magic", "Magia de pacto"),
      f(2, "eldritch-invocations", "Invocaciones sobrenaturales"),
      f(3, "pact-boon", "Don del pacto"),
      f(11, "mystic-arcanum-6", "Arcano místico (nivel 6)"),
      f(13, "mystic-arcanum-7", "Arcano místico (nivel 7)"),
      f(15, "mystic-arcanum-8", "Arcano místico (nivel 8)"),
      f(17, "mystic-arcanum-9", "Arcano místico (nivel 9)"),
      f(20, "eldritch-master", "Maestro sobrenatural"),
    ],
    subclasses: [
      {
        key: "the-fiend",
        name: "El Diablo",
        chosenAtLevel: 1,
        features: [
          f(1, "expanded-spell-list", "Lista de conjuros ampliada"),
          f(1, "dark-ones-blessing", "Bendición del oscuro"),
          f(6, "dark-ones-own-luck", "Suerte del oscuro"),
          f(10, "fiendish-resilience", "Resistencia diabólica"),
          f(14, "hurl-through-hell", "Arrojar a través del infierno"),
        ],
      },
    ],
  },
  {
    key: "wizard",
    name: "Mago",
    hitDie: 6,
    saveProficiencies: ["int", "wis"],
    armorProficiencies: [],
    weaponProficiencies: ["Dagas", "Dardos", "Hondas", "Bastones", "Ballestas ligeras"],
    skillChoice: {
      choose: 2,
      from: ["arcana", "history", "insight", "investigation", "medicine", "religion"],
    },
    spellcastingAbility: "int",
    spellProgression: "FULL",
    asiLevels: ASI_ESTANDAR,
    features: [
      f(1, "spellcasting", "Lanzamiento de conjuros"),
      f(1, "arcane-recovery", "Recuperación arcana"),
      f(2, "arcane-tradition", "Tradición arcana"),
      f(18, "spell-mastery", "Maestría con los conjuros"),
      f(20, "signature-spells", "Conjuros distintivos"),
    ],
    subclasses: [
      {
        key: "evocation",
        name: "Escuela de evocación",
        chosenAtLevel: 2,
        features: [
          f(2, "evocation-savant", "Erudito de la evocación"),
          f(2, "sculpt-spells", "Esculpir conjuros"),
          f(6, "potent-cantrip", "Truco potente"),
          f(10, "empowered-evocation", "Evocación potenciada"),
          f(14, "overchannel", "Sobrecanalizar"),
        ],
      },
    ],
  },
];
