// Fase 2D — los statblocks del SRD 5.1, la tanda declarada.
//
// **Atribución:** material del System Reference Document 5.1, © Wizards of the Coast LLC,
// CC BY 4.0. **Los nombres y la prosa son los de la traducción oficial al español publicada por
// Wizards** («Documento de referencia del sistema 5.1»), igual que hicieron `weapons.ts` y
// `armor.ts`. Ver `NOTICE.md` de la raíz.
//
// **De dónde salió cada dato, porque no salió del mismo sitio.**
// - Los **números** (CA, dados de golpe, características, competencias, sentidos, VD) vienen del
//   API de `dnd5eapi.co`, que publica el SRD 5.1 en forma legible a máquina. Transcribir a mano
//   quince fichas de números es donde se cuela la errata que nadie ve hasta la mesa.
// - Los **nombres y la prosa** vienen del PDF oficial en español, uno a uno. Dos habrían salido
//   mal por criterio: *goblin* es **«Goblin»** y no «trasgo» —«trasgos» es el colectivo de los
//   goblinoides— y *wight* es **«Tumulario»**, no «Espectro», que es el *specter* (se confirmó
//   por CA 14 y PG 45 (6d8+18) exactos).
//
// **Tres invariantes comprobadas contra los quince antes de escribir una línea de motor**, y las
// tres se prueban en `monsters-srd.spec.ts`:
// 1. Los PG dichos son la media de los dados **más el modificador de Constitución por cada dado**.
// 2. El tamaño del dado de golpe sale del tamaño de la criatura, sin una sola excepción.
// 3. El bonificador de competencia sale del VD, y toda habilidad descompone sin resto en
//    «competente» o «pericia».
//
// **Una inconsistencia de unidades, declarada y no escondida:** los datos estructurados
// (velocidades, visión en la oscuridad) están en **pies**, como el resto de la aplicación; la
// prosa citada del documento español está en **metros**, porque es una cita y alterar los números
// de dentro de una cita es donde se rompe una traducción. Está anotado en `docs/06-pendientes.md`.
//
// **Por qué solo quince.** El SRD trae unos trescientos. La tanda cubre la banda de VD que una
// mesa usa de verdad (0 a 5) y las formas que el motor tiene que saber tratar: armadura dicha y
// armadura natural, pericia (el sigilo +6 del goblin), competencia en salvación (el zombi),
// resistencias en prosa (el tumulario), ataque múltiple y reacción (el capitán bandido). El
// camino general es el statblock propio del DM. Ver la especificación de alcance de 2D, §3.

import type { Statblock } from "@dnd/shared";

export const SRD_STATBLOCKS: Statblock[] = [
  {
    ref: "SRD:commoner",
    source: "SRD",
    name: "Plebeyo",
    size: "MEDIUM",
    type: "HUMANOID",
    subtype: "cualquier raza",
    alignment: "cualquier alineamiento",
    ac: 10,
    hitDiceCount: 1,
    abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
    saveProficiencies: [],
    skillProficiencies: {},
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "uno cualquiera (normalmente común)",
    cr: 0,
    traits: [],
    actions: [
      {
        name: "Garrote",
        desc: "Ataque con arma cuerpo a cuerpo: +2 a impactar, alcance 1,5 m, un objetivo. Impacto: 2 (1d4) de daño contundente.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:bandit",
    source: "SRD",
    name: "Bandido",
    size: "MEDIUM",
    type: "HUMANOID",
    subtype: "cualquier raza",
    alignment:
      "cualquier alineamiento no legal Clase de Armadura: 12 (armadura de cuero) Puntos de golpe: 11 (2d8 + 2) Velocidad: 9 m",
    ac: 12,
    acNote: "armadura de cuero",
    hitDiceCount: 2,
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    saveProficiencies: [],
    skillProficiencies: {},
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "uno cualquiera (normalmente común)",
    cr: 0.125,
    traits: [],
    actions: [
      {
        name: "Cimitarra",
        desc: "Ataque con arma cuerpo a cuerpo: +3 a impactar, alcance 1,5 m, un objetivo. Impacto: 4 (1d6 + 1) de daño cortante.",
      },
      {
        name: "Ballesta ligera",
        desc: "Ataque con arma a distancia: +3 a impactar, alcance 24/96 m, un objetivo. Impacto: 5 (1d8 + 1) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:guard",
    source: "SRD",
    name: "Guardia",
    size: "MEDIUM",
    type: "HUMANOID",
    subtype: "cualquier raza",
    alignment: "cualquier alineamiento",
    ac: 16,
    acNote: "camisa de malla, escudo",
    hitDiceCount: 2,
    abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 11, cha: 10 },
    saveProficiencies: [],
    skillProficiencies: { perception: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "uno cualquiera (normalmente común)",
    cr: 0.125,
    traits: [],
    actions: [
      {
        name: "Lanza",
        desc: "Ataque con arma cuerpo a cuerpo o a distancia: +3 a impactar, alcance 1,5 m o 6/18 m a distancia, un objetivo. Impacto: 4 (1d6 + 1) de daño perforante o 5 (1d8 + 1) de daño perforante si se usa a dos manos en un ataque cuerpo a cuerpo.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:skeleton",
    source: "SRD",
    name: "Esqueleto",
    size: "MEDIUM",
    type: "UNDEAD",
    alignment: "legal malvado",
    ac: 13,
    acNote: "restos de armadura",
    hitDiceCount: 2,
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    saveProficiencies: [],
    skillProficiencies: {},
    damageResistances: [],
    damageImmunities: ["poison"],
    damageVulnerabilities: ["bludgeoning"],
    conditionImmunities: ["poisoned", "exhaustion"],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "entiende los idiomas que conocía en vida, pero no puede hablar",
    cr: 0.25,
    traits: [],
    actions: [
      {
        name: "Espada corta",
        desc: "Ataque con arma cuerpo a cuerpo: +4 a impactar, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante.",
      },
      {
        name: "Arco corto",
        desc: "Ataque con arma a distancia: +4 a impactar, alcance 24/96 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:goblin",
    source: "SRD",
    name: "Goblin",
    size: "SMALL",
    type: "HUMANOID",
    subtype: "trasgo",
    alignment: "neutral malvado",
    ac: 15,
    acNote: "armadura de cuero, escudo",
    hitDiceCount: 2,
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    saveProficiencies: [],
    skillProficiencies: { stealth: "expertise" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "común, goblin",
    cr: 0.25,
    traits: [
      {
        name: "Huida Veloz",
        desc: "En cada uno de sus turnos, el goblin puede usar las acciones de destrabarse o esconderse como acción adicional.",
      },
    ],
    actions: [
      {
        name: "Cimitarra",
        desc: "Ataque con arma cuerpo a cuerpo: +4 a impactar, alcance 1,5 m, un objetivo. Impacto: 5 (1d6 + 2) de daño cortante.",
      },
      {
        name: "Arco corto",
        desc: "Ataque con arma a distancia: +4 a impactar, alcance 24/96 m, un objetivo. Impacto: 5 (1d6 + 2) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:wolf",
    source: "SRD",
    name: "Lobo",
    size: "MEDIUM",
    type: "BEAST",
    alignment: "sin alineamiento",
    ac: 13,
    acNote: "armadura natural",
    hitDiceCount: 2,
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    saveProficiencies: [],
    skillProficiencies: { perception: "proficient", stealth: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    otherSenses: [],
    speeds: { walk: 40 },
    cr: 0.25,
    traits: [
      {
        name: "Atacar en Manada",
        desc: "El lobo tiene ventaja en las tiradas de ataque contra una criatura si al menos uno de los aliados del lobo se encuentra a 1,5 m o menos de la criatura y no está incapacitado.",
      },
      {
        name: "Oído y Olfato Agudos",
        desc: "El lobo tiene ventaja en las pruebas de Sabiduría (Percepción) que dependan del oído o del olfato.",
      },
    ],
    actions: [
      {
        name: "Mordisco",
        desc: "Ataque con arma cuerpo a cuerpo: +4 a impactar, alcance 1,5 m, un objetivo. Impacto: 7 (2d4 + 2) de daño perforante. Si el objetivo es una criatura, deberá superar una tirada de salvación de Fuerza con CD 11 o será derribada.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:zombie",
    source: "SRD",
    name: "Zombi",
    size: "MEDIUM",
    type: "UNDEAD",
    alignment: "neutral malvado",
    ac: 8,
    hitDiceCount: 3,
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    saveProficiencies: ["wis"],
    skillProficiencies: {},
    damageResistances: [],
    damageImmunities: ["poison"],
    damageVulnerabilities: [],
    conditionImmunities: ["poisoned"],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 20 },
    languages: "entiende los idiomas que conocía en vida, pero no puede hablar",
    cr: 0.25,
    traits: [
      {
        name: "Fortaleza de Muerto Viviente",
        desc: "Si el daño reduce a 0 los puntos de golpe del zombi, este deberá hacer una tirada de salvación de Constitución con CD 5 + el daño sufrido, siempre que este no sea radiante o proveniente de un crítico. Si tiene éxito, el zombi se queda con 1 punto de golpe.",
      },
    ],
    actions: [
      {
        name: "Golpe",
        desc: "Ataque con arma cuerpo a cuerpo: +3 a impactar, alcance 1,5 m, un objetivo. Impacto: 4 (1d6 + 1) de daño contundente.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:orc",
    source: "SRD",
    name: "Orco",
    size: "MEDIUM",
    type: "HUMANOID",
    subtype: "orco",
    alignment: "caótico malvado",
    ac: 13,
    acNote: "armadura de pieles",
    hitDiceCount: 2,
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    saveProficiencies: [],
    skillProficiencies: { intimidation: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "común, orco",
    cr: 0.5,
    traits: [
      {
        name: "Agresivo",
        desc: "Como acción adicional, el orco puede moverse hasta su velocidad hacia una criatura hostil que pueda ver.",
      },
    ],
    actions: [
      {
        name: "Hacha a dos manos",
        desc: "Ataque con arma cuerpo a cuerpo: +5 a impactar, alcance 1,5 m, un objetivo. Impacto: 9 (1d12 + 3) de daño cortante.",
      },
      {
        name: "Jabalina",
        desc: "Ataque con arma cuerpo a cuerpo o a distancia: +5 a impactar, alcance 1,5 m o 9/36 m a distancia, un objetivo. Impacto: 6 (1d6 + 3) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:dire-wolf",
    source: "SRD",
    name: "Lobo terrible",
    size: "LARGE",
    type: "BEAST",
    alignment: "sin alineamiento",
    ac: 14,
    acNote: "armadura natural",
    hitDiceCount: 5,
    abilities: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    saveProficiencies: [],
    skillProficiencies: { perception: "proficient", stealth: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    otherSenses: [],
    speeds: { walk: 50 },
    cr: 1,
    traits: [
      {
        name: "Atacar en Manada",
        desc: "El lobo tiene ventaja en una tirada de ataque contra una criatura si al menos uno de los aliados del lobo se encuentra a 1,5 m o menos de la criatura y no está incapacitado.",
      },
      {
        name: "Oído y Olfato Agudos",
        desc: "El lobo tiene ventaja en las pruebas de Sabiduría (Percepción) que dependan del oído o del olfato.",
      },
    ],
    actions: [
      {
        name: "Mordisco",
        desc: "Ataque con arma cuerpo a cuerpo: +5 a impactar, alcance 1,5 m, un objetivo. Impacto: 10 (2d6 + 3) de daño perforante. Si el objetivo es una criatura, deberá superar una tirada de salvación de Fuerza con CD 13 o será derribada.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:bandit-captain",
    source: "SRD",
    name: "Capitán bandido",
    size: "MEDIUM",
    type: "HUMANOID",
    subtype: "cualquier raza",
    alignment: "cualquier alineamiento no legal",
    ac: 15,
    acNote: "cuero tachonado",
    hitDiceCount: 10,
    abilities: { str: 15, dex: 16, con: 14, int: 14, wis: 11, cha: 14 },
    saveProficiencies: ["str", "dex", "wis"],
    skillProficiencies: { athletics: "proficient", deception: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "dos cualesquiera",
    cr: 2,
    traits: [],
    actions: [
      {
        name: "Ataque múltiple",
        desc: "El capitán realiza tres ataques cuerpo a cuerpo: dos con su cimitarra y uno con su daga. En vez de esto, el capitán puede realizar dos ataques a distancia con sus dagas.",
      },
      {
        name: "Cimitarra",
        desc: "Ataque con arma cuerpo a cuerpo: +5 a impactar, alcance 1,5 m, un objetivo. Impacto: 6 (1d6 + 3) de daño cortante.",
      },
      {
        name: "Daga",
        desc: "Ataque con arma cuerpo a cuerpo o a distancia: +5 a impactar, alcance 1,5 m o 6/18 m a distancia, un objetivo. Impacto: 5 (1d4 + 3) de daño perforante.",
      },
    ],
    reactions: [
      {
        name: "Parada",
        desc: "El capitán suma 2 a su CA contra un ataque cuerpo a cuerpo que le fuera a impactar. Para poder hacer esto, debe ver a su atacante y estar empuñando un arma cuerpo a cuerpo.",
      },
    ],
    legendaryActions: [],
  },
  {
    ref: "SRD:ogre",
    source: "SRD",
    name: "Ogro",
    size: "LARGE",
    type: "GIANT",
    alignment: "caótico malvado",
    ac: 11,
    acNote: "armadura de pieles",
    hitDiceCount: 7,
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    saveProficiencies: [],
    skillProficiencies: {},
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 40 },
    languages: "común, gigante",
    cr: 2,
    traits: [],
    actions: [
      {
        name: "Garrote grande",
        desc: "Ataque con arma cuerpo a cuerpo: +6 a impactar, alcance 1,5 m, un objetivo. Impacto: 13 (2d8 + 4) de daño contundente.",
      },
      {
        name: "Jabalina",
        desc: "Ataque con arma cuerpo a cuerpo o a distancia: +6 a impactar, alcance 1,5 m o 9/36 m a distancia, un objetivo. Impacto: 11 (2d6 + 4) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:owlbear",
    source: "SRD",
    name: "Oso lechuza",
    size: "LARGE",
    type: "MONSTROSITY",
    alignment: "sin alineamiento",
    ac: 13,
    acNote: "armadura natural",
    hitDiceCount: 7,
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    saveProficiencies: [],
    skillProficiencies: { perception: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 40 },
    cr: 3,
    traits: [
      {
        name: "Vista y Olfato Agudos",
        desc: "El oso lechuza tiene ventaja en las pruebas de Sabiduría (Percepción) que dependan de la vista o del olfato.",
      },
    ],
    actions: [
      {
        name: "Ataque múltiple",
        desc: "El oso lechuza realiza dos ataques: uno con su pico y uno con sus garras.",
      },
      {
        name: "Garras",
        desc: "Ataque con arma cuerpo a cuerpo: +7 a impactar, alcance 1,5 m, un objetivo. Impacto: 14 (2d8 + 5) de daño cortante.",
      },
      {
        name: "Pico",
        desc: "Ataque con arma cuerpo a cuerpo: +7 a impactar, alcance 1,5 m, una criatura. Impacto: 10 (1d10 + 5) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:wight",
    source: "SRD",
    name: "Tumulario",
    size: "MEDIUM",
    type: "UNDEAD",
    alignment: "neutral malvado",
    ac: 14,
    acNote: "cuero tachonado",
    hitDiceCount: 6,
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    saveProficiencies: [],
    skillProficiencies: { perception: "proficient", stealth: "proficient" },
    damageResistances: [
      "necrotic",
      "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
    ],
    damageImmunities: ["poison"],
    damageVulnerabilities: [],
    conditionImmunities: ["exhaustion", "poisoned"],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "los idiomas que conocía en vida",
    cr: 3,
    traits: [
      {
        name: "Sensibilidad a la Luz Solar",
        desc: "Bajo la luz del sol, el tumulario tiene desventaja en las tiradas de ataque y las pruebas de Sabiduría (Percepción) que dependan de la vista.",
      },
    ],
    actions: [
      {
        name: "Ataque múltiple",
        desc: "El tumulario realiza dos ataques con su espada larga o dos ataques con su arco largo. Puede usar consumir vida en lugar de uno de los ataques con espada larga.",
      },
      {
        name: "Consumir vida",
        desc: "Ataque con arma cuerpo a cuerpo: +4 a impactar, alcance 1,5 m, una criatura. Impacto: 5 (1d6 + 2) de daño necrótico. El objetivo deberá superar una tirada de salvación de Constitución con CD 13 o sus puntos de golpe máximos se reducirán en una cantidad igual al daño recibido. La reducción dura hasta que el objetivo finalice un descanso largo. El objetivo muere si este efecto reduce sus puntos de golpe máximos a 0. Un humanoide que muera por este ataque se alzará 24 horas después como un zombi bajo el control del tumulario, a menos que se le devuelva a la vida o su cuerpo sea destruido. El tumulario no puede tener más de doce zombis bajo su control a la vez.",
      },
      {
        name: "Espada larga",
        desc: "Ataque con arma cuerpo a cuerpo: +4 a impactar, alcance 1,5 m, un objetivo. Impacto: 6 (1d8 + 2) de daño cortante o 7 (1d10 + 2) de daño cortante si se usa a dos manos.",
      },
      {
        name: "Arco largo",
        desc: "Ataque con arma a distancia: +4 a impactar, alcance 45/180 m, un objetivo. Impacto: 6 (1d8 + 2) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:hill-giant",
    source: "SRD",
    name: "Gigante de las colinas",
    size: "HUGE",
    type: "GIANT",
    alignment: "caótico malvado",
    ac: 13,
    acNote: "armadura natural",
    hitDiceCount: 10,
    abilities: { str: 21, dex: 8, con: 19, int: 5, wis: 9, cha: 6 },
    saveProficiencies: [],
    skillProficiencies: { perception: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    otherSenses: [],
    speeds: { walk: 40 },
    languages: "gigante",
    cr: 5,
    traits: [],
    actions: [
      { name: "Ataque múltiple", desc: "El gigante realiza dos ataques con su garrote grande." },
      {
        name: "Garrote grande",
        desc: "Ataque con arma cuerpo a cuerpo: +8 a impactar, alcance 3 m, un objetivo. Impacto: 18 (3d8 + 5) de daño contundente.",
      },
      {
        name: "Piedra",
        desc: "Ataque con arma a distancia: +8 a impactar, alcance 18/72 m, un objetivo. Impacto: 21 (3d10 + 5) de daño contundente.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
  {
    ref: "SRD:troll",
    source: "SRD",
    name: "Troll",
    size: "LARGE",
    type: "GIANT",
    alignment: "caótico malvado",
    ac: 15,
    acNote: "armadura natural",
    hitDiceCount: 8,
    abilities: { str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7 },
    saveProficiencies: [],
    skillProficiencies: { perception: "proficient" },
    damageResistances: [],
    damageImmunities: [],
    damageVulnerabilities: [],
    conditionImmunities: [],
    darkvisionFeet: 60,
    otherSenses: [],
    speeds: { walk: 30 },
    languages: "gigante",
    cr: 5,
    traits: [
      {
        name: "Olfato Agudo",
        desc: "El troll tiene ventaja en las pruebas de Sabiduría (Percepción) que dependan del olfato.",
      },
      {
        name: "Regeneración",
        desc: "El troll recupera 10 puntos de golpe al principio de su turno. Si recibe daño de ácido o de fuego, este atributo no funcionará al principio de su siguiente turno. El troll solo morirá si empieza su turno con 0 puntos de golpe y no se regenera.",
      },
    ],
    actions: [
      {
        name: "Ataque múltiple",
        desc: "El troll realiza tres ataques: uno con su mordisco y dos con sus garras.",
      },
      {
        name: "Garra",
        desc: "Ataque con arma cuerpo a cuerpo: +7 a impactar, alcance 1,5 m, un objetivo. Impacto: 11 (2d6 + 4) de daño cortante.",
      },
      {
        name: "Mordisco",
        desc: "Ataque con arma cuerpo a cuerpo: +7 a impactar, alcance 1,5 m, un objetivo. Impacto: 7 (1d6 + 4) de daño perforante.",
      },
    ],
    reactions: [],
    legendaryActions: [],
  },
];

/** Índice por `ref`, para que nadie recorra la lista buscando un goblin. */
export const SRD_STATBLOCK_POR_REF: ReadonlyMap<string, Statblock> = new Map(
  SRD_STATBLOCKS.map((s) => [s.ref, s]),
);
