// Tarea 2B — carril A1: las armas del SRD 5.1, tabla completa.
//
// **Atribución:** material del System Reference Document 5.1, © Wizards of the Coast LLC,
// CC BY 4.0. **Los nombres son los de la traducción oficial al español publicada por Wizards**
// (tabla «Armas» del «Documento de referencia del sistema 5.1»), igual que hizo `armor.ts`.
// Ver `NOTICE.md` de la raíz.
//
// **Unidades**: peso en **onzas** (16 oz = 1 lb, el SRD lo da en libras) y precio en **piezas
// de cobre** (1 po = 100 pc, 1 pp = 10 pc) — el mismo principio de `packages/shared/src/item.schema.ts`:
// la unidad íntegra abajo, la legible arriba.
//
// **Dos ausencias declaradas.** `weaponDataSchema` (`packages/shared/src/item.schema.ts`) exige
// `damageDice` con forma de dado (`damageDiceSchema`: `1d4`…`1d100`) y `damageType` en toda
// arma, y estas dos filas del SRD no encajan en ese molde sin inventar un dato que el SRD no da:
// - **Red (`net`)**: no hace daño. Su única propiedad mecánica es inmovilizar (`SPECIAL`),
//   no un `damageDice`.
// - **Cerbatana (`blowgun`)**: el SRD la da a **1 de daño perforante fijo**, no un dado — y
//   `damageDiceSchema` no acepta `1d1` ni un entero suelto (solo d4, d6, d8, d10, d12, d20, d100).
//
// Las dos se dejan fuera a propósito en vez de transcribir un dado de mentira que la traza
// enseñaría como si el SRD lo dijera.

import type { DamageType, WeaponCategory, WeaponProperty, WeaponRange } from "@dnd/shared";

export interface SrdWeapon {
  key: string;
  name: string;
  category: WeaponCategory;
  range: WeaponRange;
  damageDice: string;
  damageType: DamageType;
  properties: WeaponProperty[];
  /** El dado a dos manos de un arma versátil. Solo con `VERSATILE`. */
  versatileDice?: string;
  /** Alcance normal y largo en pies. En cuerpo a cuerpo, solo si es `THROWN`. */
  rangeNormalFt?: number;
  rangeLongFt?: number;
  weightOz: number;
  costCp: number;
}

export const SRD_WEAPONS: SrdWeapon[] = [
  // --- Armas simples cuerpo a cuerpo ---
  {
    key: "club",
    name: "Garrote",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d4",
    damageType: "BLUDGEONING",
    properties: ["LIGHT"],
    weightOz: 32,
    costCp: 10,
  },
  {
    key: "dagger",
    name: "Daga",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d4",
    damageType: "PIERCING",
    properties: ["FINESSE", "LIGHT", "THROWN"],
    rangeNormalFt: 20,
    rangeLongFt: 60,
    weightOz: 16,
    costCp: 200,
  },
  {
    key: "greatclub",
    name: "Garrote grande",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "BLUDGEONING",
    properties: ["TWO_HANDED"],
    weightOz: 160,
    costCp: 20,
  },
  {
    key: "handaxe",
    name: "Hacha de mano",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "SLASHING",
    properties: ["LIGHT", "THROWN"],
    rangeNormalFt: 20,
    rangeLongFt: 60,
    weightOz: 32,
    costCp: 500,
  },
  {
    key: "javelin",
    name: "Jabalina",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "PIERCING",
    properties: ["THROWN"],
    rangeNormalFt: 30,
    rangeLongFt: 120,
    weightOz: 32,
    costCp: 50,
  },
  {
    key: "light-hammer",
    name: "Martillo ligero",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d4",
    damageType: "BLUDGEONING",
    properties: ["LIGHT", "THROWN"],
    rangeNormalFt: 20,
    rangeLongFt: 60,
    weightOz: 32,
    costCp: 200,
  },
  {
    key: "mace",
    name: "Maza",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "BLUDGEONING",
    properties: [],
    weightOz: 64,
    costCp: 500,
  },
  {
    key: "quarterstaff",
    name: "Bastón",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "BLUDGEONING",
    properties: ["VERSATILE"],
    versatileDice: "1d8",
    weightOz: 64,
    costCp: 20,
  },
  {
    key: "sickle",
    name: "Hoz",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d4",
    damageType: "SLASHING",
    properties: ["LIGHT"],
    weightOz: 32,
    costCp: 100,
  },
  {
    key: "spear",
    name: "Lanza",
    category: "SIMPLE",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "PIERCING",
    properties: ["THROWN", "VERSATILE"],
    versatileDice: "1d8",
    rangeNormalFt: 20,
    rangeLongFt: 60,
    weightOz: 48,
    costCp: 100,
  },

  // --- Armas simples a distancia ---
  {
    key: "light-crossbow",
    name: "Ballesta ligera",
    category: "SIMPLE",
    range: "RANGED",
    damageDice: "1d8",
    damageType: "PIERCING",
    properties: ["AMMUNITION", "LOADING", "TWO_HANDED"],
    rangeNormalFt: 80,
    rangeLongFt: 320,
    weightOz: 80,
    costCp: 2500,
  },
  {
    key: "dart",
    name: "Dardo",
    category: "SIMPLE",
    range: "RANGED",
    damageDice: "1d4",
    damageType: "PIERCING",
    properties: ["FINESSE", "THROWN"],
    rangeNormalFt: 20,
    rangeLongFt: 60,
    weightOz: 4,
    costCp: 5,
  },
  {
    key: "shortbow",
    name: "Arco corto",
    category: "SIMPLE",
    range: "RANGED",
    damageDice: "1d6",
    damageType: "PIERCING",
    properties: ["AMMUNITION", "TWO_HANDED"],
    rangeNormalFt: 80,
    rangeLongFt: 320,
    weightOz: 32,
    costCp: 2500,
  },
  {
    key: "sling",
    name: "Honda",
    category: "SIMPLE",
    range: "RANGED",
    damageDice: "1d4",
    damageType: "BLUDGEONING",
    properties: ["AMMUNITION"],
    rangeNormalFt: 30,
    rangeLongFt: 120,
    weightOz: 0,
    costCp: 10,
  },

  // --- Armas marciales cuerpo a cuerpo ---
  {
    key: "battleaxe",
    name: "Hacha de batalla",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "SLASHING",
    properties: ["VERSATILE"],
    versatileDice: "1d10",
    weightOz: 64,
    costCp: 1000,
  },
  {
    key: "flail",
    name: "Mangual",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "BLUDGEONING",
    properties: [],
    weightOz: 32,
    costCp: 1000,
  },
  {
    key: "glaive",
    name: "Guja",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d10",
    damageType: "SLASHING",
    properties: ["HEAVY", "REACH", "TWO_HANDED"],
    weightOz: 96,
    costCp: 2000,
  },
  {
    key: "greataxe",
    name: "Hacha grande",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d12",
    damageType: "SLASHING",
    properties: ["HEAVY", "TWO_HANDED"],
    weightOz: 112,
    costCp: 3000,
  },
  {
    key: "greatsword",
    name: "Mandoble",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "2d6",
    damageType: "SLASHING",
    properties: ["HEAVY", "TWO_HANDED"],
    weightOz: 96,
    costCp: 5000,
  },
  {
    key: "halberd",
    name: "Alabarda",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d10",
    damageType: "SLASHING",
    properties: ["HEAVY", "REACH", "TWO_HANDED"],
    weightOz: 96,
    costCp: 2000,
  },
  {
    key: "lance",
    name: "Lanza de caballería",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d12",
    damageType: "PIERCING",
    properties: ["REACH", "SPECIAL"],
    weightOz: 96,
    costCp: 1000,
  },
  {
    key: "long-sword",
    name: "Espada larga",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "SLASHING",
    properties: ["VERSATILE"],
    versatileDice: "1d10",
    weightOz: 48,
    costCp: 1500,
  },
  {
    key: "maul",
    name: "Almádena",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "2d6",
    damageType: "BLUDGEONING",
    properties: ["HEAVY", "TWO_HANDED"],
    weightOz: 160,
    costCp: 1000,
  },
  {
    key: "morningstar",
    name: "Lucero del alba",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "PIERCING",
    properties: [],
    weightOz: 64,
    costCp: 1500,
  },
  {
    key: "pike",
    name: "Pica",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d10",
    damageType: "PIERCING",
    properties: ["HEAVY", "REACH", "TWO_HANDED"],
    weightOz: 288,
    costCp: 500,
  },
  {
    key: "rapier",
    name: "Estoque",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "PIERCING",
    properties: ["FINESSE"],
    weightOz: 32,
    costCp: 2500,
  },
  {
    key: "scimitar",
    name: "Cimitarra",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "SLASHING",
    properties: ["FINESSE", "LIGHT"],
    weightOz: 48,
    costCp: 2500,
  },
  {
    key: "short-sword",
    name: "Espada corta",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "PIERCING",
    properties: ["FINESSE", "LIGHT"],
    weightOz: 32,
    costCp: 1000,
  },
  {
    key: "trident",
    name: "Tridente",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d6",
    damageType: "PIERCING",
    properties: ["THROWN", "VERSATILE"],
    versatileDice: "1d8",
    rangeNormalFt: 20,
    rangeLongFt: 60,
    weightOz: 64,
    costCp: 500,
  },
  {
    key: "war-pick",
    name: "Pico de guerra",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "PIERCING",
    properties: [],
    weightOz: 32,
    costCp: 500,
  },
  {
    key: "warhammer",
    name: "Martillo de guerra",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d8",
    damageType: "BLUDGEONING",
    properties: ["VERSATILE"],
    versatileDice: "1d10",
    weightOz: 32,
    costCp: 1500,
  },
  {
    key: "whip",
    name: "Látigo",
    category: "MARTIAL",
    range: "MELEE",
    damageDice: "1d4",
    damageType: "SLASHING",
    properties: ["FINESSE", "REACH"],
    weightOz: 48,
    costCp: 200,
  },

  // --- Armas marciales a distancia ---
  // (La cerbatana falta a propósito — ver la nota de cabecera: su daño del SRD es «1» fijo,
  // no un dado, y no encaja en `damageDiceSchema`.)
  {
    key: "hand-crossbow",
    name: "Ballesta de mano",
    category: "MARTIAL",
    range: "RANGED",
    damageDice: "1d6",
    damageType: "PIERCING",
    properties: ["AMMUNITION", "LIGHT", "LOADING"],
    rangeNormalFt: 30,
    rangeLongFt: 120,
    weightOz: 48,
    costCp: 7500,
  },
  {
    key: "heavy-crossbow",
    name: "Ballesta pesada",
    category: "MARTIAL",
    range: "RANGED",
    damageDice: "1d10",
    damageType: "PIERCING",
    properties: ["AMMUNITION", "HEAVY", "LOADING", "TWO_HANDED"],
    rangeNormalFt: 100,
    rangeLongFt: 400,
    weightOz: 288,
    costCp: 5000,
  },
  {
    key: "longbow",
    name: "Arco largo",
    category: "MARTIAL",
    range: "RANGED",
    damageDice: "1d8",
    damageType: "PIERCING",
    properties: ["AMMUNITION", "HEAVY", "TWO_HANDED"],
    rangeNormalFt: 150,
    rangeLongFt: 600,
    weightOz: 32,
    costCp: 5000,
  },
];
